services:
  web:
    build: ./app
    command: gunicorn p2p_spread.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  rabbitmq:
    image: rabbitmq:3.11.13-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    build: ./app
    command: celery -A p2p_spread worker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web

  celery-beat:
    build: ./app
    command: celery -A p2p_spread beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web
      - celery
