services:
  web:
    build: ./app
    command: gunicorn p2p_spread.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
      - static_volume:/static
    expose:
      - "8000"
    depends_on:
      - rabbitmq
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/static
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  rabbitmq:
    image: rabbitmq:3.11.13-management
    hostname: rabbitmq
    expose:
      - "15672"
      - "5672"
    restart: always

  celery:
    build: ./app
    command: celery -A p2p_spread worker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web
    restart: always

  celery-beat:
    build: ./app
    command: celery -A p2p_spread beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web
      - celery
    restart: always

  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    restart: always

volumes:
  static_volume:
  postgresql_volume:
