services:
  web:
    build: ./app
    command: gunicorn p2p_spread.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
      - static_volume:/static
    expose:
      - "8000"
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/static
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3.11.13-management
    hostname: rabbitmq
    expose:
      - "15672"
      - "5672"

  celery:
    build: ./app
    command: celery -A p2p_spread worker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web

  celery-beat:
    build: ./app
    command: celery -A p2p_spread beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - web
      - celery

volumes:
  static_volume: