# Generated by Django 4.2 on 2023-04-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('abbr', models.CharField(max_length=4)),
                ('is_fiat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('binance_name', models.CharField(default='test', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=4)),
                ('asset', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='currency.currency')),
                ('fiat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fiat', to='currency.currency')),
                ('payment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='currency.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('pair', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='currency.pair')),
            ],
        ),
        migrations.CreateModel(
            name='Chain2Reverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default=0)),
                ('backward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='backward_chain', to='currency.chain2')),
                ('forward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='forward_chain', to='currency.chain2')),
            ],
        ),
        migrations.AddField(
            model_name='chain2',
            name='buy_pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buy_pair', to='currency.pair'),
        ),
        migrations.AddField(
            model_name='chain2',
            name='sell_pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sell_pair', to='currency.pair'),
        ),
    ]
