# Generated by Django 4.2 on 2023-04-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain2Reverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default=0)),
                ('backward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='backward_chain', to='currency.chain2')),
                ('forward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='forward_chain', to='currency.chain2')),
            ],
        ),
    ]
