# Generated by Django 4.1.7 on 2023-04-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='currency1',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='currency2',
        ),
        migrations.AddField(
            model_name='pair',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='pair',
            name='fiat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fiat', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='pair',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='binance_name',
            field=models.CharField(default='test', max_length=45),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_fiat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.CharField(max_length=45),
        ),
    ]
