# Generated by Django 4.2.2 on 2023-07-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currenciesspot_chain3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain3Reverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default=0)),
                ('backward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='backward_chain3', to='currency.chain3')),
                ('forward_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='forward_chain3', to='currency.chain3')),
            ],
        ),
    ]
